#!/bin/sh
#
#  Script to start consul-template
#
#  Copyright (C) 2018 opsgang, Martin Dobrev
#

source /env

exec /usr/local/bin/consul-template \
  -config /etc/consul-template/config.hcl \
  -consul-addr="$CONSUL_ADDR" \
  -template="/tmp/nginx.env.ctmpl:/etc/nginx/nginx.env:/sbin/boot_nginx.sh" \
  -template="/tmp/haproxy.conf.ctmpl:/etc/haproxy/haproxy.conf:/sbin/boot_haproxy.sh"
