#!/bin/sh
#
#  Script to start consul-template
#
#  Copyright (C) 2018 opsgang, Martin Dobrev
#

source /env

exec /usr/local/bin/consul-template \
  -consul-addr="$CONSUL_ADDR" \
  -template="/tmp/haproxy.conf.ctmpl:/etc/haproxy/haproxy.conf:/sbin/boot_haproxy.sh" \
  -wait=3s:11s \
  -dedup
