#!/bin/sh

main() {
  export SERVICE_1275_NAME=${SERVICE_1275_NAME:-"${SERVICE_80_NAME}-peers"}

  # Test if Consul address has been set and if not assume we run in ECS so try to
  # get the IP of the host system
  if test -z "$CONSUL_ADDR"; then
    PRIV_IP=`curl -sL http://169.254.169.254/latest/meta-data/local-ipv4`
    # Did we receive a response from AWS?
    if test -z "$PRIV_IP"; then
      export CONSUL_ADDR="consul:8500"
    else
      export CONSUL_ADDR="$PRIV_IP:8500"
    fi
  fi
  
  # Dump environment
  export > /env

  trap onterm SIGTERM SIGINT

  echo "Starting runit"
  /sbin/runsvdir-start &
  wait "$!"
}

onterm() {
  echo "Exiting..."
  pkill -SIGHUP runsvdir-start
  exit $?
}

main "$@"
